### ISSUE TITLE
Reflect and rotate test and block constructor

### ISSUE THREAD

**Issue by Saiyara-Islam-123** [ssantoshp/comp250Tester#15]
Hi
I am passing reflect and rotate tests but they don't work properly in the game.

Also, is the block constructor supposed to raise an illegal argument exception when the size isn't a power of 2 that can be subdivided until we hit the max depth? Isn't it the job of the update size and position method? The pdf doesn't explicitly mention throwing an exception for block constructor.

**Comment by SamZhang02** [comment]
Hi Sayara,
> I am passing reflect and rotate tests but they don't work properly in the game.

This can be due to a multitude of reasons. The testers provided by the Prof and other students unfortunately can't test for every case. A few things you might wanna check out for: are you sure that your rotate and reflect
- Change the coordinates?
- Change the position in the children array?

> Also, is the block constructor supposed to raise an illegal argument exception when the size isn't a power of 2 that can be subdivided until we hit the max depth?

The tests for the constructor were entirely provided by the Prof and TAs, it might be better to ask this question on Ed.
